package com.example.maziyyah.mood_tracker.model;

import java.util.UUID;

public class LovedOne {

    private String loveOneId; // Autogenerated lovedOneId
    private String name;
    private String contact;
    private String relationship;
    private Long chatId; // will be added after getting details?
    
    public LovedOne() {
    }


    public LovedOne(String name, String contact, String relationship) {
        this.loveOneId = UUID.randomUUID().toString();
        this.name = name;
        this.contact = contact;
        this.relationship = relationship;
        // not sure if chatId should be in the constructor..it will be null at first
    }





    public String getName() {
        return name;
    }
    public void setName(String name) {
        this.name = name;
    }
    public String getContact() {
        return contact;
    }
    public void setContact(String contact) {
        this.contact = contact;
    }
    public String getRelationship() {
        return relationship;
    }
    public void setRelationship(String relationship) {
        this.relationship = relationship;
    }
    public Long getChatId() {
        return chatId;
    }
    public void setChatId(Long chatId) {
        this.chatId = chatId;
    }
    public String getLoveOneId() {
        return loveOneId;
    }
    public void setLoveOneId(String loveOneId) {
        this.loveOneId = loveOneId;
    }

    

    

    
}
