package com.example.maziyyah.mood_tracker.model;

import java.time.LocalDateTime;
import java.time.ZoneId;

import org.apache.commons.math3.random.RandomDataGenerator;

public class MoodEntryV1 {

    private String moodEntryId; // generated?

    private String userId; // this was autogenerated when you created the user -> has to pass this information
    private Integer moodScore;
    private String note;
    private LocalDateTime timestamp;

    
    public MoodEntryV1() {
    }

    public MoodEntryV1(String userId, Integer moodScore, String note, LocalDateTime timestamp) {

        RandomDataGenerator randomDataGenerator = new RandomDataGenerator();
        String randomPart = randomDataGenerator.nextHexString(8); //8-character hex
        this.moodEntryId = userId.substring(0,4) + randomPart;
        this.userId = userId;
        this.moodScore = moodScore;
        this.note = note;
        this.timestamp = timestamp;
    }

    // Convert LocalDateTime to epoch milliseconds
    public long getTimestampAsEpoch() {
        return this.timestamp.atZone(ZoneId.systemDefault()).toInstant().toEpochMilli();
    }

    // Convert epoch milliseconds to LocalDateTime (static for reuse)
    public static LocalDateTime fromEpochToLocalDateTime(long epochMillis) {
        return LocalDateTime.ofInstant(
                    java.time.Instant.ofEpochMilli(epochMillis), 
                    ZoneId.systemDefault());
    }


    @Override
    public String toString() {
        return  moodEntryId + "," + userId + "," + moodScore + "," + "["
                + note + "]" + "," + getTimestampAsEpoch();
    }

    public String getMoodEntryId() {
        return moodEntryId;
    }



    public void setMoodEntryId(String moodEntryId) {
        this.moodEntryId = moodEntryId;
    }



    public String getUserId() {
        return userId;
    }



    public void setUserId(String userId) {
        this.userId = userId;
    }



    public Integer getMoodScore() {
        return moodScore;
    }



    public void setMoodScore(Integer moodScore) {
        this.moodScore = moodScore;
    }



    public String getNote() {
        return note;
    }



    public void setNote(String note) {
        this.note = note;
    }



    public LocalDateTime getTimestamp() {
        return timestamp;
    }



    public void setTimestamp(LocalDateTime timestamp) {
        this.timestamp = timestamp;
    }


    

    
}
